config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :facts do
    get :admin, on: :collection
  end
  resources :paragraphs do
    get :admin, on: :collection
  end
  resources :riddles do
    get :admin, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
end

app/models/riddle.rb
class Riddle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: %i[ show edit update destroy ]

  # GET /facts or /facts.json
  def index
    @facts = Fact.all
  end

  def admin
    @facts = Fact.all
  end

  # GET /facts/1 or /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts or /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: "Fact was successfully created." }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1 or /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to @fact, notice: "Fact was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1 or /facts/1.json
  def destroy
    @fact.destroy!

    respond_to do |format|
      format.html { redirect_to facts_path, notice: "Fact was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def fact_params
      params.expect(fact: [ :name, :description ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @facts     = Fact.all.order(id: :desc).limit(3)
    @riddles   = Riddle.all.order(id: :desc).limit(3)
    @paragraph = Paragraph.all.order(id: :desc).first
  end
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: %i[ show edit update destroy ]

  # GET /paragraphs or /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  def admin
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1 or /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs or /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: "Paragraph was successfully created." }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1 or /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph, notice: "Paragraph was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1 or /paragraphs/1.json
  def destroy
    @paragraph.destroy!

    respond_to do |format|
      format.html { redirect_to paragraphs_path, notice: "Paragraph was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def paragraph_params
      params.expect(paragraph: [ :title, :content ])
    end
end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController
  before_action :set_riddle, only: %i[ show edit update destroy ]

  # GET /riddles or /riddles.json
  def index
    @riddles = Riddle.all
  end

  def admin
    @riddles = Riddle.all
  end

  # GET /riddles/1 or /riddles/1.json
  def show
  end

  # GET /riddles/new
  def new
    @riddle = Riddle.new
  end

  # GET /riddles/1/edit
  def edit
  end

  # POST /riddles or /riddles.json
  def create
    @riddle = Riddle.new(riddle_params)

    respond_to do |format|
      if @riddle.save
        format.html { redirect_to @riddle, notice: "Riddle was successfully created." }
        format.json { render :show, status: :created, location: @riddle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @riddle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riddles/1 or /riddles/1.json
  def update
    respond_to do |format|
      if @riddle.update(riddle_params)
        format.html { redirect_to @riddle, notice: "Riddle was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @riddle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @riddle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riddles/1 or /riddles/1.json
  def destroy
    @riddle.destroy!

    respond_to do |format|
      format.html { redirect_to riddles_path, notice: "Riddle was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_riddle
      @riddle = Riddle.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def riddle_params
      params.expect(riddle: [ :hint, :answer ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/helpers/riddles_helper.rb
module RiddlesHelper
end

app/views/facts/_fact.html.erb
<li class="fact" id="<%= dom_id fact %>">
  <span class="name"><%= fact.name %></span>
  <p class="description">
    <%= fact.description %>
  </p>
</li>

app/views/facts/_form.html.erb
<%= form_with(model: fact) do |form| %>
  <% if fact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
        <% fact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/facts/admin.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Facts" %>

<h1>Facts</h1>

<%= link_to 'New Fact', new_fact_path %>

<ul class="facts">
  <% @facts.each do |fact| %>
    <%= render fact %>
    <%= link_to 'Edit this Fact', edit_fact_path(fact) %>
  <% end %>
</ul>

app/views/facts/edit.html.erb
<% content_for :title, "Editing fact" %>

<h1>Editing fact</h1>

<%= render "form", fact: @fact %>

<br>

<div>
  <%= link_to "Back to facts", admin_facts_path %>
</div>

app/views/facts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Facts" %>

<h1>Facts</h1>

<div id="facts">
  <% @facts.each do |fact| %>
    <%= render fact %>
    <p>
      <%= link_to "Show this fact", fact %>
    </p>
  <% end %>
</div>

<%= link_to "New fact", new_fact_path %>

app/views/facts/new.html.erb
<% content_for :title, "New fact" %>

<h1>New fact</h1>

<%= render "form", fact: @fact %>

<br>

<div>
  <%= link_to "Back to facts", facts_path %>
</div>

app/views/facts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fact %>

<div>
  <%= link_to "Edit this fact", edit_fact_path(@fact) %> |
  <%= link_to "Back to facts", facts_path %>

  <%= button_to "Destroy this fact", @fact, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Animal Facts & More</h1>
<h3>by KERRY SLAYMAKER</h3>
<p>
  Welcome to Animal Facts!
</p>

<p>
  Here are some of our newest animal facts:
</p>
<ul class="facts">
  <% @facts.each do |fact| -%>
    <%= render fact %>
  <% end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animalfacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="header">
      <span class="title">Animal Facts & More</span>
      <div class="links">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Facts', facts_path %>
        <%= link_to 'Riddles', riddles_path %>
        <%= link_to 'Paragraphs', paragraphs_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/paragraphs/_form.html.erb
<%= form_with(model: paragraph) do |form| %>
  <% if paragraph.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
        <% paragraph.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/paragraphs/_paragraph.html.erb
<div id="<%= dom_id paragraph %>">
  <p class="title">
    <%= paragraph.title %>
  </p>
  <p class="content">
    <%= paragraph.content %>
  </p>
</div>

app/views/paragraphs/admin.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Paragraphs" %>

<h1>Paragraphs</h1>

<%= link_to 'New Paragraph', new_paragraph_path %>

<ul class="paragraphs">
  <% @paragraphs.each do |paragraph| %>
    <%= render paragraph %>
    <%= link_to 'Edit this Paragraph', edit_paragraph_path(paragraph) %>
  <% end %>
</ul>

app/views/paragraphs/edit.html.erb
<% content_for :title, "Editing paragraph" %>

<h1>Editing paragraph</h1>

<%= render "form", paragraph: @paragraph %>

<br>

<div>
  <%= link_to "Back to paragraphs", admin_paragraphs_path %>
</div>

app/views/paragraphs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Paragraphs" %>

<h1>Paragraphs</h1>

<div id="paragraphs">
  <% @paragraphs.each do |paragraph| %>
    <%= render paragraph %>
    <p>
      <%= link_to "Show this paragraph", paragraph %>
    </p>
  <% end %>
</div>

app/views/paragraphs/new.html.erb
<% content_for :title, "New paragraph" %>

<h1>New paragraph</h1>

<%= render "form", paragraph: @paragraph %>

<br>

<div>
  <%= link_to "Back to paragraphs", admin_paragraphs_path %>
</div>

app/views/paragraphs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paragraph %>

<div>
  <%= link_to "Edit this paragraph", edit_paragraph_path(@paragraph) %> |
  <%= link_to "Back to paragraphs", paragraphs_path %>

  <%= button_to "Destroy this paragraph", @paragraph, method: :delete %>
</div>

app/views/riddles/_form.html.erb
<%= form_with(model: riddle) do |form| %>
  <% if riddle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(riddle.errors.count, "error") %> prohibited this riddle from being saved:</h2>

      <ul>
        <% riddle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :hint, style: "display: block" %>
    <%= form.textarea :hint %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.textarea :answer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/riddles/_riddle.html.erb
<div id="<%= dom_id riddle %>">
  <p class="hint">
    <%= riddle.hint %>
  </p>
  <p class="answer">
    <%= riddle.answer %>
  </p>
</div>

app/views/riddles/admin.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Riddles" %>

<h1>Riddles</h1>

<%= link_to 'New Riddle', new_riddle_path %>

<ul class="riddles">
  <% @riddles.each do |riddle| %>
    <%= render riddle %>
    <%= link_to 'Edit this Riddle', edit_riddle_path(riddle) %>
  <% end %>
</ul>

<%= link_to "New riddle", new_riddle_path %>

app/views/riddles/edit.html.erb
<% content_for :title, "Editing riddle" %>

<h1>Editing riddle</h1>

<%= render "form", riddle: @riddle %>

<br>

<div>
  <%= link_to "Back to riddles", admin_riddles_path %>
</div>

app/views/riddles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Riddles" %>

<h1>Riddles</h1>

<div id="riddles">
  <% @riddles.each do |riddle| %>
    <%= render riddle %>
  <% end %>
</div>

app/views/riddles/new.html.erb
<% content_for :title, "New riddle" %>

<h1>New riddle</h1>

<%= render "form", riddle: @riddle %>

<br>

<div>
  <%= link_to "Back to riddles", admin_riddles_path %>
</div>

app/views/riddles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @riddle %>

<div>
  <%= link_to "Edit this riddle", edit_riddle_path(@riddle) %> |
  <%= link_to "Back to riddles", riddles_path %>

  <%= button_to "Destroy this riddle", @riddle, method: :delete %>
</div>